services:
  wordpress:
    depends_on:
      - database
    image: wordpress:6.4
    container_name: stijncappetijn-wordpress
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: '${MYSQL_HOST}'
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - ./wp-content:/var/www/html/wp-content:z
      - ./themes/wp_theme_external_site_rest_api:/var/www/html/wp-content/themes/wp_theme_external_site_rest_api:z
      - ./plugins/stijncappetijn_siteconfiguration:/var/www/html/wp-content/plugins/stijncappetijn_siteconfiguration:z
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:z


  database:
    image: mysql:8.3
    container_name: stijncappetijn-database
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
