name: Deploy to remote web server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.REMOTE_SSH_KEY }}
        script: |
          cd ~/stijncappetijn-wp-theme
          git pull origin main
          docker-compose build
          docker-compose down
          docker-compose up --build -d

    - name: Notify
      uses: peter-evans/create-issue@v3
      with:
        title: Deployment successful
        body: The application has been successfully deployed.
